# Generated by Django 5.0.4 on 2024-05-20 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaccommodation',
            name='status',
            field=models.IntegerField(default=1, editable=False),
        ),
        migrations.AlterField(
            model_name='commentrequest',
            name='status',
            field=models.IntegerField(default=1, editable=False),
        ),
        migrations.AlterField(
            model_name='follow',
            name='status',
            field=models.IntegerField(default=1, editable=False),
        ),
        migrations.AlterField(
            model_name='likeaccommodation',
            name='status',
            field=models.IntegerField(default=1, editable=False),
        ),
        migrations.AlterField(
            model_name='likerequest',
            name='status',
            field=models.IntegerField(default=1, editable=False),
        ),
        migrations.AlterField(
            model_name='postaccommodation',
            name='status',
            field=models.IntegerField(default=1, editable=False),
        ),
        migrations.AlterField(
            model_name='postrequest',
            name='status',
            field=models.IntegerField(default=1, editable=False),
        ),
    ]
