# Generated by Django 5.0.4 on 2024-05-23 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0002_alter_postaccommodation_current_people_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postaccommodation',
            name='max_people',
            field=models.IntegerField(default=1),
        ),
    ]
