# Generated by Django 5.0.4 on 2024-05-23 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0003_alter_postaccommodation_max_people'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postaccommodation',
            name='current_people',
            field=models.IntegerField(default=1),
        ),
    ]
