# Generated by Django 5.0.4 on 2024-06-01 13:15

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0004_alter_postaccommodation_current_people'),
    ]

    operations = [
        migrations.AddField(
            model_name='postrequest',
            name='city',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='postrequest',
            name='district',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='postrequest',
            name='max_price',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='postrequest',
            name='min_price',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='postrequest',
            name='quanity',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='postrequest',
            name='room_type',
            field=models.CharField(choices=[('SH', 'Shared'), ('PR', 'Private')], default='SH', max_length=2),
        ),
        migrations.AddField(
            model_name='postrequest',
            name='title',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='postrequest',
            name='description',
            field=ckeditor.fields.RichTextField(default=None),
        ),
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('follower', 'owner')},
        ),
    ]
