# Generated by Django 5.0.4 on 2024-06-01 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0006_remove_postrequest_area_postrequest_acreage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postrequest',
            name='quanity',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
