# Generated by Django 5.0.4 on 2024-06-14 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0007_alter_postrequest_quanity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postrequest',
            name='acreage',
        ),
        migrations.AddField(
            model_name='postaccommodation',
            name='ward',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='postrequest',
            name='gender',
            field=models.BooleanField(default=1),
        ),
    ]
