# Generated by Django 5.0.4 on 2024-06-14 04:37

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0008_remove_postrequest_acreage_postaccommodation_ward_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postaccommodation',
            name='main_image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True),
        ),
    ]
