const data = {
  "Chọn thành phố": ["Chọn quận/huyện"],
  "An Giang": [
    "Long Xuyen",
    "Chau Doc",
    "Tan Chau",
    "An Phu",
    "Chau Phu",
    "Chau Thanh",
    "Cho Moi",
    "Phu Tan",
    "Thot Not",
    "Tri Ton",
  ],
  "Ba Ria-Vung Tau": [
    "Vung Tau",
    "Ba Ria",
    "Chau Duc",
    "Con Dao",
    "Dat Do",
    "Long Dien",
    "Tan Thanh",
    "Xuyen Moc",
  ],
  "Bac Giang": [
    "Bac Giang",
    "Hiep Hoa",
    "Lang Giang",
    "Luc Nam",
    "Luc Ngan",
    "Son Dong",
    "Tan Yen",
    "Viet Yen",
    "Yen Dung",
    "Yen The",
  ],
  "Bac Kan": [
    "Bac Kan",
    "Ba Be",
    "Bach Thong",
    "Cho Don",
    "Cho Moi",
    "Na Ri",
    "Ngan Son",
    "Pac Nam",
  ],
  "Bac Lieu": [
    "Bac Lieu",
    "Dong Hai",
    "Gia Rai",
    "Hoa Binh",
    "Hong Dan",
    "Phuoc Long",
    "Vinh Loi",
  ],
  "Bac Ninh": [
    "Bac Ninh",
    "Gia Binh",
    "Luong Tai",
    "Que Vo",
    "Thuan Thanh",
    "Tien Du",
    "Tu Son",
    "Yen Phong",
  ],
  "Ben Tre": [
    "Ben Tre",
    "Ba Tri",
    "Binh Dai",
    "Chau Thanh",
    "Cho Lach",
    "Giong Trom",
    "Mo Cay Bac",
    "Mo Cay Nam",
    "Thanh Phu",
  ],
  "Binh Dinh": [
    "Quy Nhon",
    "An Lao",
    "An Nhon",
    "Hoai An",
    "Hoai Nhon",
    "Phu Cat",
    "Phu My",
    "Tay Son",
    "Tuy Phuoc",
    "Vinh Thanh",
  ],
  "Binh Duong": [
    "Thu Dau Mot",
    "Ben Cat",
    "Bac Tan Uyen",
    "Dau Tieng",
    "Di An",
    "Phu Giao",
    "Tan Uyen",
    "Thuan An",
  ],
  "Binh Phuoc": [
    "Dong Xoai",
    "Binh Long",
    "Bu Dang",
    "Bu Dop",
    "Bu Gia Map",
    "Chon Thanh",
    "Dong Phu",
    "Hon Quan",
    "Loc Ninh",
    "Phu Rieng",
  ],
  "Binh Thuan": [
    "Phan Thiet",
    "La Gi",
    "Bac Binh",
    "Duc Linh",
    "Ham Tan",
    "Ham Thuan Bac",
    "Ham Thuan Nam",
    "Phu Quy",
    "Tanh Linh",
    "Tuy Phong",
  ],
  "Ca Mau": [
    "Ca Mau",
    "Cai Nuoc",
    "Dam Doi",
    "Nam Can",
    "Ngoc Hien",
    "Phu Tan",
    "Thoi Binh",
    "Tran Van Thoi",
    "U Minh",
  ],
  "Can Tho": [
    "Ninh Kieu",
    "Binh Thuy",
    "Cai Rang",
    "O Mon",
    "Phong Dien",
    "Thot Not",
    "Vinh Thanh",
    "Co Do",
    "Thoi Lai",
  ],
  "Cao Bang": [
    "Cao Bang",
    "Bao Lac",
    "Bao Lam",
    "Ha Lang",
    "Ha Quang",
    "Hoa An",
    "Nguyen Binh",
    "Phuc Hoa",
    "Quang Hoa",
    "Thach An",
    "Thong Nong",
  ],
  "Da Nang": [
    "Hai Chau",
    "Thanh Khe",
    "Son Tra",
    "Ngu Hanh Son",
    "Lien Chieu",
    "Cam Le",
    "Hoa Vang",
    "Hoang Sa",
  ],
  "Dak Lak": [
    "Buon Ma Thuot",
    "Buon Don",
    "Cu Kuin",
    "Ea H'leo",
    "Ea Kar",
    "Ea Sup",
    "Krong Ana",
    "Krong Bong",
    "Krong Buk",
    "Krong Nang",
    "Krong Pac",
    "Lak",
    "M'Drak",
  ],
  "Dak Nong": [
    "Gia Nghia",
    "Cu Jut",
    "Dak Glong",
    "Dak Mil",
    "Dak R'Lap",
    "Dak Song",
    "Krong No",
    "Tuy Duc",
  ],
  "Dien Bien": [
    "Dien Bien Phu",
    "Muong Lay",
    "Dien Bien",
    "Dien Bien Dong",
    "Muong Ang",
    "Nam Po",
    "Tua Chua",
    "Tuan Giao",
  ],
  "Dong Nai": [
    "Bien Hoa",
    "Long Khanh",
    "Cam My",
    "Dinh Quan",
    "Long Thanh",
    "Nhon Trach",
    "Thong Nhat",
    "Trang Bom",
    "Tan Phu",
    "Vinh Cuu",
    "Xuan Loc",
  ],
  "Dong Thap": [
    "Cao Lanh",
    "Hong Ngu",
    "Sa Dec",
    "Chau Thanh",
    "Hong Ngu",
    "Lap Vo",
    "Lai Vung",
    "Tam Nong",
    "Tan Hong",
    "Thanh Binh",
    "Thap Muoi",
  ],
  "Gia Lai": [
    "Pleiku",
    "An Khe",
    "Ayun Pa",
    "Chu Pah",
    "Chu Prong",
    "Chu Se",
    "Dak Doa",
    "Dak Po",
    "Ia Grai",
    "Ia Pa",
    "KBang",
    "Kong Chro",
    "Krong Pa",
    "Mang Yang",
    "Phu Thien",
  ],
  "Ha Giang": [
    "Ha Giang",
    "Bac Me",
    "Bac Quang",
    "Dong Van",
    "Hoang Su Phi",
    "Meo Vac",
    "Quan Ba",
    "Quang Binh",
    "Quang Ba",
    "Vi Xuyen",
    "Xin Man",
    "Yen Minh",
  ],
  "Ha Nam": [
    "Phu Ly",
    "Binh Luc",
    "Duy Tien",
    "Kim Bang",
    "Ly Nhan",
    "Thanh Liem",
  ],
  "Ha Tinh": [
    "Ha Tinh",
    "Hong Linh",
    "Ky Anh",
    "Bac Ha",
    "Cam Xuyen",
    "Can Loc",
    "Duc Tho",
    "Huong Khe",
    "Huong Son",
    "Ky Anh",
    "Loc Ha",
    "Nghi Xuan",
    "Thach Ha",
    "Vu Quang",
  ],
  "Hai Duong": [
    "Hai Duong",
    "Chi Linh",
    "Binh Giang",
    "Cam Giang",
    "Gia Loc",
    "Kim Thanh",
    "Kinh Mon",
    "Nam Sach",
    "Ninh Giang",
    "Thanh Ha",
    "Thanh Mien",
    "Tu Ky",
  ],
  "Hai Phong": [
    "Hong Bang",
    "Ngo Quyen",
    "Le Chan",
    "Kien An",
    "Hai An",
    "Duong Kinh",
    "Do Son",
    "Thuy Nguyen",
    "An Duong",
    "An Lao",
    "Tien Lang",
    "Vinh Bao",
    "Kien Thuy",
    "Cat Hai",
    "Bach Long Vy",
  ],
  "Hau Giang": [
    "Vi Thanh",
    "Nga Bay",
    "Long My",
    "Phung Hiep",
    "Vi Thuy",
    "Chau Thanh A",
    "Chau Thanh",
  ],
  "Hoa Binh": [
    "Hoa Binh",
    "Cao Phong",
    "Da Bac",
    "Kim Boi",
    "Lac Son",
    "Lac Thuy",
    "Luong Son",
    "Mai Chau",
    "Tan Lac",
    "Yen Thuy",
  ],
  "Hung Yen": [
    "Hung Yen",
    "An Thi",
    "Khoai Chau",
    "Kim Dong",
    "My Hao",
    "Phu Cu",
    "Tien Lu",
    "Van Giang",
    "Van Lam",
    "Yen My",
  ],
  "Khanh Hoa": [
    "Nha Trang",
    "Cam Ranh",
    "Cam Lam",
    "Dien Khanh",
    "Khanh Son",
    "Khanh Vinh",
    "Ninh Hoa",
    "Truong Sa",
    "Van Ninh",
  ],
  "Kien Giang": [
    "Rach Gia",
    "Ha Tien",
    "An Bien",
    "An Minh",
    "Chau Thanh",
    "Giang Thanh",
    "Go Quao",
    "Giong Rieng",
    "Hon Dat",
    "Kien Hai",
    "Kien Luong",
    "Phu Quoc",
    "Tan Hiep",
    "U Minh Thuong",
    "Vinh Thuan",
  ],
  "Kon Tum": [
    "Kon Tum",
    "Dak Glei",
    "Dak Ha",
    "Dak To",
    "Ia H'Drai",
    "Kon Plong",
    "Kon Ray",
    "Ngoc Hoi",
    "Sa Thay",
    "Tu Mo Rong",
  ],
  "Lai Chau": [
    "Lai Chau",
    "Muong Te",
    "Phong Tho",
    "Sin Ho",
    "Tam Duong",
    "Tan Uyen",
    "Than Uyen",
    "Nam Nhun",
  ],
  "Lam Dong": [
    "Da Lat",
    "Bao Loc",
    "Bao Lam",
    "Cat Tien",
    "Da Huoai",
    "Da Teh",
    "Don Duong",
    "Duc Trong",
    "Lac Duong",
    "Lam Ha",
  ],
  "Lang Son": [
    "Lang Son",
    "Bac Son",
    "Binh Gia",
    "Cao Loc",
    "Chi Lang",
    "Dinh Lap",
    "Huu Lung",
    "Loc Binh",
    "Trang Dinh",
    "Van Lang",
    "Van Quan",
  ],
  "Lao Cai": [
    "Lao Cai",
    "Bac Ha",
    "Bao Thang",
    "Bao Yen",
    "Bat Xat",
    "Muong Khuong",
    "Sa Pa",
    "Si Ma Cai",
    "Van Ban",
  ],
  "Long An": [
    "Tan An",
    "Ben Luc",
    "Can Duoc",
    "Can Giuoc",
    "Chau Thanh",
    "Duc Hoa",
    "Duc Hue",
    "Kien Tuong",
    "Moc Hoa",
    "Tan Hung",
    "Tan Thanh",
    "Thanh Hoa",
    "Thu Thua",
    "Vinh Hung",
  ],
  "Nam Dinh": [
    "Nam Dinh",
    "Giao Thuy",
    "Hai Hau",
    "My Loc",
    "Nam Truc",
    "Nghia Hung",
    "Truc Ninh",
    "Vu Ban",
    "Xuan Truong",
    "Y Yen",
  ],
  "Nghe An": [
    "Vinh",
    "Cua Lo",
    "Thai Hoa",
    "Hoang Mai",
    "Anh Son",
    "Con Cuong",
    "Dien Chau",
    "Do Luong",
    "Hung Nguyen",
    "Ky Son",
    "Nam Dan",
    "Nghi Loc",
    "Nghia Dan",
    "Que Phong",
    "Quy Chau",
    "Quy Hop",
    "Tan Ky",
    "Thanh Chuong",
    "Tuong Duong",
    "Yen Thanh",
  ],
  "Ninh Binh": [
    "Ninh Binh",
    "Tam Diep",
    "Gia Vien",
    "Hoa Lu",
    "Kim Son",
    "Nho Quan",
    "Yen Khanh",
    "Yen Mo",
  ],
  "Ninh Thuan": [
    "Phan Rang - Thap Cham",
    "Bac Ai",
    "Ninh Hai",
    "Ninh Phuoc",
    "Ninh Son",
    "Thuan Bac",
    "Thuan Nam",
  ],
  "Phu Tho": [
    "Viet Tri",
    "Phu Tho",
    "Cam Khe",
    "Doan Hung",
    "Ha Hoa",
    "Lam Thao",
    "Phong Chau",
    "Phu Ninh",
    "Tam Nong",
    "Tan Son",
    "Thanh Ba",
    "Thanh Son",
    "Thanh Thuy",
    "Yen Lap",
  ],
  "Phu Yen": [
    "Tuy Hoa",
    "Song Cau",
    "Dong Hoa",
    "Dong Xuan",
    "Phu Hoa",
    "Son Hoa",
    "Tay Hoa",
    "Tuy An",
  ],
  "Quang Binh": [
    "Dong Hoi",
    "Ba Don",
    "Bo Trach",
    "Le Thuy",
    "Minh Hoa",
    "Quang Ninh",
    "Quang Trach",
    "Tuyen Hoa",
  ],
  "Quang Nam": [
    "Tam Ky",
    "Hoi An",
    "Dien Ban",
    "Bac Tra My",
    "Dong Giang",
    "Duy Xuyen",
    "Hiep Duc",
    "Nam Giang",
    "Nam Tra My",
    "Nong Son",
    "Nui Thanh",
    "Phu Ninh",
    "Phuoc Son",
    "Que Son",
    "Tay Giang",
    "Thang Binh",
    "Tien Phuoc",
  ],
  "Quang Ngai": [
    "Quang Ngai",
    "Duc Pho",
    "Ba To",
    "Binh Son",
    "Ly Son",
    "Minh Long",
    "Mo Duc",
    "Nghia Hanh",
    "Son Ha",
    "Son Tay",
    "Son Tinh",
    "Tay Tra",
    "Tra Bong",
    "Tu Nghia",
  ],
  "Quang Ninh": [
    "Ha Long",
    "Cam Pha",
    "Mong Cai",
    "Uong Bi",
    "Binh Lieu",
    "Co To",
    "Dam Ha",
    "Dong Trieu",
    "Hai Ha",
    "Hoanh Bo",
    "Quang Yen",
    "Tien Yen",
    "Van Don",
  ],
  "Quang Tri": [
    "Dong Ha",
    "Quang Tri",
    "Cam Lo",
    "Con Co",
    "Gio Linh",
    "Hai Lang",
    "Huong Hoa",
    "Trieu Phong",
    "Vinh Linh",
  ],
  "Soc Trang": [
    "Soc Trang",
    "Nga Nam",
    "Vinh Chau",
    "Chau Thanh",
    "Cu Lao Dung",
    "Ke Sach",
    "Long Phu",
    "My Tu",
    "My Xuyen",
    "Thanh Tri",
    "Tran De",
  ],
  "Son La": [
    "Son La",
    "Moc Chau",
    "Bac Yen",
    "Mai Son",
    "Moc Chau",
    "Muong La",
    "Phu Yen",
    "Quynh Nhai",
    "Song Ma",
    "Sop Cop",
    "Thuan Chau",
    "Van Ho",
    "Yen Chau",
  ],
  "Tay Ninh": [
    "Tay Ninh",
    "Hoa Thanh",
    "Tan Chau",
    "Tan Bien",
    "Ben Cau",
    "Chau Thanh",
    "Duong Minh Chau",
    "Go Dau",
    "Trang Bang",
  ],
  "Thai Binh": [
    "Thai Binh",
    "Dong Hung",
    "Hung Ha",
    "Kien Xuong",
    "Quynh Phu",
    "Thai Thuy",
    "Tien Hai",
    "Vu Thu",
  ],
  "Thai Nguyen": [
    "Thai Nguyen",
    "Song Cong",
    "Pho Yen",
    "Dai Tu",
    "Dinh Hoa",
    "Dong Hy",
    "Phu Binh",
    "Phu Luong",
    "Vo Nhai",
  ],
  "Thanh Hoa": [
    "Thanh Hoa",
    "Bim Son",
    "Sam Son",
    "Ba Thuoc",
    "Cam Thuy",
    "Dong Son",
    "Ha Trung",
    "Hau Loc",
    "Hoang Hoa",
    "Lang Chanh",
    "Mong Lat",
    "Nga Son",
    "Ngoc Lac",
    "Nhu Thanh",
    "Nhu Xuan",
    "Nong Cong",
    "Quan Hoa",
    "Quan Son",
    "Quang Xuong",
    "Thach Thanh",
    "Thieu Hoa",
    "Thuong Xuan",
    "Tinh Gia",
    "Trieu Son",
    "Vinh Loc",
    "Yen Dinh",
  ],
  "Thua Thien Hue": [
    "Hue",
    "Huong Thuy",
    "Huong Tra",
    "A Luoi",
    "Nam Dong",
    "Phong Dien",
    "Phu Loc",
    "Phu Vang",
    "Quang Dien",
  ],
  "Tien Giang": [
    "My Tho",
    "Cai Lay",
    "Cai Be",
    "Chau Thanh",
    "Cho Gao",
    "Go Cong",
    "Go Cong Dong",
    "Go Cong Tay",
    "Tan Phu Dong",
    "Tan Phuoc",
  ],
  "Tra Vinh": [
    "Tra Vinh",
    "Cang Long",
    "Cau Ke",
    "Cau Ngang",
    "Chau Thanh",
    "Duyen Hai",
    "Tieu Can",
    "Tra Cu",
  ],
  "Tuyen Quang": [
    "Tuyen Quang",
    "Chiem Hoa",
    "Ham Yen",
    "Lam Binh",
    "Na Hang",
    "Son Duong",
    "Yen Son",
  ],
  "Vinh Long": [
    "Vinh Long",
    "Binh Minh",
    "Binh Tan",
    "Long Ho",
    "Mang Thit",
    "Tam Binh",
    "Tra On",
    "Vung Liem",
  ],
  "Vinh Phuc": [
    "Vinh Yen",
    "Phuc Yen",
    "Binh Xuyen",
    "Lap Thach",
    "Song Lo",
    "Tam Dao",
    "Tam Duong",
    "Vinh Tuong",
    "Yen Lac",
  ],
  "Yen Bai": [
    "Yen Bai",
    "Nghia Lo",
    "Mu Cang Chai",
    "Luc Yen",
    "Tram Tau",
    "Tran Yen",
    "Van Chan",
    "Van Yen",
    "Yen Binh",
  ],
};

export default data;
